/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/review/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recovery/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prepare/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["buildSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prepare/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prepare/job-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestJobText"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prepare/job-synthesize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["synthesizeJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prepare/job-file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestJobFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prepare/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["diagnose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas/unique-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uniqueName"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mistakes/mastered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setMastered"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/wait-finished": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["waitFinished"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/mute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["mute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["interrupt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["hint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/finish-early": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishEarly"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/engine/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post: operations["save_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["probe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coding/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coding/judge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["judge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coding/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trends/overall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trends/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dimensions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["turns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["load"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mistakes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mistakes/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["topics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mistakes/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["resumes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/keys/{provider_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["keyPresent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audioDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mistakes/{mistake_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateReviewBody: {
            /** Format: int32 */
            session_id?: number;
        };
        AbandonedSkill: {
            skill: string;
            domain: string;
            /** Format: int32 */
            abandoned_at_depth: number;
            /** Format: int32 */
            attempts: number;
        };
        /** @enum {string} */
        AnnotationKind: "strength" | "weakness" | "filler" | "off_topic";
        AnswerRewrite: {
            /** Format: int32 */
            question_index: number;
            question: string;
            original: string;
            rewritten: string;
            why_better: string[];
            used_assets: string[];
        };
        DimensionScore: {
            dimension: components["schemas"]["ScoreDimension"];
            /** Format: double */
            score: number;
            reason: string;
            evidence: string[];
        };
        DrillItem: {
            action: string;
            why: string;
            time_cost: string;
        };
        /** @enum {string} */
        GapSeverity: "blocker" | "major" | "minor";
        ImprovementPlan: {
            focus_area: string;
            diagnosis: string;
            expected_gain: string;
            drills: components["schemas"]["DrillItem"][];
            resources: string[];
            next_mock_setup: string;
        };
        MistakeItem: {
            knowledge_point: string;
            topic: string;
            question: string;
            candidate_answer: string;
            key_points: string[];
            severity: components["schemas"]["GapSeverity"];
            review_hint: string;
        };
        ProsodyReport: {
            /** Format: double */
            words_per_minute: number;
            /** Format: double */
            filler_ratio: number;
            /** Format: double */
            pause_ratio: number;
            /** Format: int64 */
            longest_pause_ms: number;
            /** Format: double */
            speaking_ratio: number;
            /** Format: int32 */
            interrupted_count: number;
            per_question: components["schemas"]["QuestionProsody"][];
            verdict: string;
        };
        QuestionProsody: {
            /** Format: int32 */
            question_index: number;
            /** Format: double */
            words_per_minute: number;
            /** Format: int32 */
            filler_count: number;
            /** Format: double */
            pause_ratio: number;
            /** Format: int64 */
            longest_pause_ms: number;
        };
        ReviewReport: {
            /** Format: int32 */
            session_id: number;
            /** Format: int64 */
            duration_ms: number;
            reviewable: boolean;
            /** Format: double */
            overall_score: number;
            headline: string;
            summary: string;
            dimensions: components["schemas"]["DimensionScore"][];
            annotations: components["schemas"]["TranscriptAnnotation"][];
            rewrites: components["schemas"]["AnswerRewrite"][];
            mistakes: components["schemas"]["MistakeItem"][];
            prosody: components["schemas"]["ProsodyReport"];
            strengths: string[];
            improvements: string[];
            next_actions: string[];
            improvement_plans: components["schemas"]["ImprovementPlan"][];
            abandoned_skills: components["schemas"]["AbandonedSkill"][];
            degraded_sections: string[];
        };
        /** @enum {string} */
        ScoreDimension: "tech_depth" | "expression" | "resilience" | "value_fit" | "coding" | "collaboration";
        TranscriptAnnotation: {
            /** Format: int32 */
            turn_index: number;
            kind: components["schemas"]["AnnotationKind"];
            quote: string;
            comment: string;
        };
        InterruptedSession: {
            /** Format: int32 */
            session_id: number;
            title: string;
            /** Format: int64 */
            duration_ms: number;
            reviewable: boolean;
        };
        BuildSessionBody: {
            task_id?: string;
            persona: components["schemas"]["PersonaContract"];
            /** Format: int32 */
            resume_id?: number | null;
            /** Format: int32 */
            job_id?: number | null;
            tier: components["schemas"]["CompanyTier"];
            level: components["schemas"]["JobLevel"];
            /** Format: int32 */
            minutes?: number;
            coding_enabled?: boolean;
        };
        /** @enum {string} */
        CompanyTier: "big_tech" | "mid_tech" | "startup" | "manufacturing" | "state_owned" | "foreign" | "finance" | "outsource";
        /** @enum {string} */
        JobLevel: "intern" | "junior" | "mid" | "senior" | "expert";
        /** @enum {string} */
        PersonaArchetype: "irritable_cto" | "gentle_hr" | "picky_biz_leader" | "foreign_corp" | "academic_purist" | "silent_observer" | "rapid_fire" | "structured" | "custom";
        PersonaContract: {
            /** Format: int32 */
            id: number | null;
            name: string;
            archetype: components["schemas"]["PersonaArchetype"];
            company_tier: components["schemas"]["CompanyTier"];
            job_title: string;
            company_flavor: string;
            voice: string;
            speech: components["schemas"]["SpeechStyle"];
            pressure: components["schemas"]["PressureProfile"];
            probing: components["schemas"]["ProbingProfile"];
            opening_line: string;
            extra_rules: string[];
            builtin: boolean;
            is_builtin: boolean;
        };
        PressureProfile: {
            /** Format: int32 */
            aggression: number;
            /** Format: int32 */
            interrupt_tendency: number;
            /** Format: int32 */
            silence_pressure: number;
            /** Format: int32 */
            challenge_frequency: number;
            /** Format: int32 */
            tolerance_for_vagueness: number;
        };
        ProbingProfile: {
            /** Format: int32 */
            divergence: number;
            /** Format: int32 */
            follow_up_depth: number;
            /** Format: int32 */
            project_focus: number;
            /** Format: int32 */
            fundamentals_focus: number;
            /** Format: int32 */
            system_design_focus: number;
            /** Format: int32 */
            coding_focus: number;
            /** Format: int32 */
            behavioral_focus: number;
        };
        SpeechStyle: {
            /** Format: int32 */
            code_switch: number;
            /** Format: int32 */
            verbosity: number;
            /** Format: int32 */
            warmth: number;
            /** Format: int32 */
            formality: number;
            /** Format: int32 */
            speech_rate: number;
            catchphrases: string[];
            banned_phrases: string[];
        };
        BankQuestion: {
            /** Format: int32 */
            id: number;
            text: string;
            skill: string;
            domain: string;
            /** Format: int32 */
            depth: number;
            source: components["schemas"]["QuestionSource"];
            project_ref: string;
            jd_ref: string;
            follow_ups: string[];
            expected_signals: string[];
            must_ask: boolean;
        };
        /** @enum {string|null} */
        DepthAction: "deepen" | "sidestep" | "switch" | "abandon" | null;
        /** @enum {string} */
        DriftKind: "none" | "ai_self_reveal" | "role_swap" | "refusal" | "off_domain" | "style_break" | "answer_leak";
        /** @enum {string} */
        InterviewPhase: "warmup" | "resume_deep_dive" | "tech_depth" | "behavioral" | "coding" | "stress" | "candidate_qa" | "closing" | "finished";
        InterviewPlan: {
            /** Format: int64 */
            total_ms: number;
            slots: components["schemas"]["PhaseSlot"][];
        };
        InterviewState: {
            /** Format: int32 */
            session_id: number;
            persona: components["schemas"]["PersonaContract"];
            plan: components["schemas"]["InterviewPlan"];
            bank: components["schemas"]["QuestionBank"];
            company_tier: components["schemas"]["CompanyTier"];
            job_level: components["schemas"]["JobLevel"];
            job_title: string;
            resume_digest: string;
            jd_digest: string;
            gap_digest: string;
            phase: components["schemas"]["InterviewPhase"];
            /** Format: int64 */
            phase_started_at_ms: number;
            /** Format: int64 */
            elapsed_ms: number;
            /** Format: int32 */
            turn_index: number;
            /** Format: int32 */
            question_index: number;
            turns: components["schemas"]["TurnRecord"][];
            questions: components["schemas"]["QuestionRecord"][];
            /** Format: int32 */
            current_question_index: number | null;
            /** Format: int32 */
            follow_up_depth: number;
            pending_skills: string[];
            covered_skills: string[];
            asked_bank_ids: number[];
            skill_progress: {
                [key: string]: components["schemas"]["SkillProgress"];
            };
            domains_visited: string[];
            current_domain: string;
            last_depth_action: components["schemas"]["DepthAction"] | null;
            /** Format: int32 */
            questions_since_personality: number;
            /** Format: int32 */
            personality_probes_used: number;
            /** Format: int32 */
            interrupts_used_in_phase: number;
            /** Format: int32 */
            drift_count: number;
            last_drift: components["schemas"]["DriftKind"];
            /** Format: int32 */
            turns_since_reanchor: number;
            star: components["schemas"]["StarState"];
            live_scores: {
                [key: string]: number;
            };
            coding_active: boolean;
            code_language: string;
            code_snapshot: string;
            reviewable: boolean;
        };
        PhaseSlot: {
            phase: components["schemas"]["InterviewPhase"];
            /** Format: int64 */
            budget_ms: number;
            /** Format: int32 */
            min_questions: number;
        };
        QuestionBank: {
            questions: components["schemas"]["BankQuestion"][];
        };
        QuestionRecord: {
            /** Format: int32 */
            index: number;
            phase: components["schemas"]["InterviewPhase"];
            intent: components["schemas"]["TurnIntent"];
            brief: string;
            target_skill: string;
            domain: string;
            /** Format: int32 */
            depth: number;
            /** Format: int32 */
            bank_question_id: number | null;
            spoken_text: string;
            /** Format: int64 */
            asked_at_ms: number;
            /** Format: int32 */
            follow_up_depth: number;
            answer_text: string;
            /** Format: double */
            quality: number | null;
            depth_action: components["schemas"]["DepthAction"] | null;
        };
        /** @enum {string} */
        QuestionSource: "jd" | "project" | "skill" | "coding" | "fundamental" | "behavioral";
        SkillProgress: {
            skill: string;
            domain: string;
            /** Format: int32 */
            depth_reached: number;
            /** Format: int32 */
            attempts: number;
            /** Format: int32 */
            attempts_at_depth: number;
            /** Format: int32 */
            low_streak: number;
            /** Format: double */
            best_quality: number;
            exhausted: boolean;
            /** Format: int32 */
            abandoned_at_depth: number;
        };
        /** @enum {string} */
        Speaker: "interviewer" | "candidate";
        /** @enum {string} */
        StarElement: "situation" | "task" | "action" | "result";
        StarState: {
            present: components["schemas"]["StarElement"][];
            /** Format: int32 */
            probes_used: number;
            behavioral: boolean;
            is_behavioral: boolean;
        };
        /** @enum {string} */
        TurnIntent: "ask_new" | "follow_up" | "star_probe" | "boundary_test" | "interrupt" | "pressure" | "acknowledge" | "transition" | "coding_handoff" | "close";
        TurnRecord: {
            /** Format: int32 */
            index: number;
            speaker: components["schemas"]["Speaker"];
            text: string;
            /** Format: int64 */
            started_at_ms: number;
            /** Format: int64 */
            duration_ms: number;
            intent: components["schemas"]["TurnIntent"] | null;
            was_interrupted: boolean;
            /** Format: int32 */
            question_index: number | null;
        };
        IngestPathBody: {
            task_id?: string;
            path: string;
        };
        ProjectHighlight: {
            name: string;
            role: string;
            stack: string[];
            impact: string;
            summary: string;
        };
        ResumeProfile: {
            source_name: string;
            raw_text: string;
            candidate_name: string;
            /** Format: double */
            years_of_experience: number;
            current_title: string;
            skills: string[];
            projects: components["schemas"]["ProjectHighlight"][];
            education: string;
            self_claims: string[];
        };
        StoredResume: {
            /** Format: int32 */
            id: number;
            label: string;
            file_path: string;
            profile: components["schemas"]["ResumeProfile"];
        };
        IngestJobTextBody: {
            task_id?: string;
            raw: string;
        };
        JobDescription: {
            source_name: string;
            raw_text: string;
            company: string;
            title: string;
            must_have: string[];
            nice_to_have: string[];
            responsibilities: string[];
        };
        StoredJob: {
            /** Format: int32 */
            id: number;
            label: string;
            job: components["schemas"]["JobDescription"];
        };
        SynthesizeJobBody: {
            task_id?: string;
            title: string;
            tier: components["schemas"]["CompanyTier"];
            level: components["schemas"]["JobLevel"];
            extra?: string;
        };
        DiagnoseBody: {
            task_id?: string;
            /** Format: int32 */
            resume_id?: number;
            /** Format: int32 */
            job_id?: number;
            refresh?: boolean;
        };
        GapReport: {
            /** Format: int32 */
            match_score: number;
            verdict: string;
            matches: components["schemas"]["SkillMatch"][];
            gaps: components["schemas"]["SkillGap"][];
            predicted_questions: string[];
            focus_skills: string[];
            phase_emphasis: {
                [key: string]: number;
            };
        };
        SkillGap: {
            skill: string;
            severity: components["schemas"]["GapSeverity"];
            jd_requirement: string;
            why_gap: string;
            bridge_asset: string;
            talking_script: string;
            study_hint: string;
        };
        SkillMatch: {
            skill: string;
            evidence: string;
            /** Format: int32 */
            strength: number;
        };
        StoredGap: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            resume_id: number;
            /** Format: int32 */
            job_id: number;
            report: components["schemas"]["GapReport"];
        };
        UniqueNameBody: {
            base: string;
        };
        SetMasteredBody: {
            /** Format: int32 */
            mistake_id?: number;
            mastered?: boolean;
        };
        Ok: {
            ok: boolean;
        };
        StopInterviewBody: {
            aborted?: boolean;
        };
        StopResult: {
            /** Format: int32 */
            session_id: number | null;
            reviewable: boolean;
            /** Format: int64 */
            elapsed_ms: number;
        };
        StartInterviewBody: {
            /** Format: int32 */
            session_id?: number;
        };
        MuteBody: {
            muted?: boolean;
        };
        HintBody: {
            auto?: boolean;
        };
        SubmitCodeBody: {
            language: string;
            source?: string;
        };
        AppSettings: {
            roles: {
                [key: string]: components["schemas"]["RoleBinding"];
            };
            realtime: components["schemas"]["RealtimeSettings"];
            audio: components["schemas"]["AudioSettings"];
            orchestration: components["schemas"]["OrchestrationSettings"];
            features: components["schemas"]["FeatureSettings"];
            custom_chat: components["schemas"]["CustomEndpoint"];
            active_profile_name: string;
        };
        AudioSettings: {
            input_device: string;
            output_device: string;
            /** Format: double */
            input_gain: number;
            /** Format: double */
            vad_threshold: number;
            /** Format: int32 */
            silence_duration_ms: number;
            /** Format: int32 */
            prefix_padding_ms: number;
            semantic_vad: boolean;
            auto_gain: boolean;
            /** Format: double */
            learned_gain: number;
            /** Format: int32 */
            playback_buffer_ms: number;
        };
        CustomEndpoint: {
            base_url: string;
            models: string[];
        };
        FeatureSettings: {
            copilot_enabled: boolean;
            coding_round_enabled: boolean;
            save_audio: boolean;
        };
        OrchestrationSettings: {
            /** Format: int32 */
            reanchor_every_turns: number;
            /** Format: int32 */
            max_follow_up_depth: number;
            /** Format: int32 */
            director_timeout_ms: number;
            /** Format: int32 */
            guard_timeout_ms: number;
            /** Format: int32 */
            interrupt_budget_per_phase: number;
            /** Format: double */
            verbose_seconds_before_interrupt: number;
            /** Format: int32 */
            turn_gap_ms: number;
            /** Format: int32 */
            planned_minutes: number;
        };
        RealtimeSettings: {
            provider: string;
            model: string;
            voice: string;
            /** Format: double */
            temperature: number;
        };
        RoleBinding: {
            provider: string;
            model: string;
        };
        ProbeBody: {
            provider_key: string;
            model?: string;
            api_key?: string;
            realtime?: boolean;
        };
        ProbeOutcome: {
            ok: boolean;
            detail: string;
            /** Format: int64 */
            latency_ms: number;
        };
        ApiKeyBody: {
            provider_key: string;
            api_key?: string;
        };
        RunCodeBody: {
            language: string;
            source?: string;
            stdin?: string;
        };
        RunOutcome: {
            ok: boolean;
            stdout: string;
            stderr: string;
            /** Format: int32 */
            exit_code: number;
            /** Format: int64 */
            duration_ms: number;
            timed_out: boolean;
        };
        CodingCase: {
            input: string;
            expected: string;
            note: string;
        };
        JudgeCodeBody: {
            language: string;
            source?: string;
            cases?: components["schemas"]["CodingCase"][];
        };
        CaseOutcome: {
            /** Format: int32 */
            index: number;
            passed: boolean;
            input: string;
            expected: string;
            actual: string;
            stderr: string;
            /** Format: int64 */
            duration_ms: number;
            timed_out: boolean;
        };
        JudgeOutcome: {
            /** Format: int32 */
            passed: number;
            /** Format: int32 */
            total: number;
            cases: components["schemas"]["CaseOutcome"][];
        };
        ComposeChallengeBody: {
            skill?: string;
        };
        CodingChallenge: {
            title: string;
            statement: string;
            io_format: string;
            starter: {
                [key: string]: string;
            };
            reference: {
                [key: string]: string;
            };
            cases: components["schemas"]["CodingCase"][];
            hints: string[];
        };
        TrendPoint: {
            /** Format: int32 */
            session_id: number;
            /** Format: date-time */
            recorded_at: string;
            /** Format: double */
            score: number;
        };
        /** @enum {string} */
        SessionStatus: "draft" | "running" | "reviewing" | "completed" | "aborted";
        SessionSummary: {
            /** Format: int32 */
            id: number;
            title: string;
            status: components["schemas"]["SessionStatus"];
            persona_name: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int32 */
            duration_ms: number;
            /** Format: double */
            overall_score: number | null;
            /** Format: int32 */
            planned_minutes: number;
        };
        GlobalStats: {
            /** Format: int32 */
            total_sessions: number;
            /** Format: int32 */
            completed_sessions: number;
            /** Format: int32 */
            total_minutes: number;
            /** Format: double */
            best_score: number | null;
            /** Format: double */
            latest_score: number | null;
            /** Format: double */
            average_score: number | null;
        };
        StoredMistake: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            session_id: number | null;
            item: components["schemas"]["MistakeItem"];
            /** Format: int32 */
            hit_count: number;
            mastered: boolean;
            /** Format: date-time */
            last_seen_at: string;
        };
        MistakeCounts: {
            /** Format: int32 */
            pending: number;
            /** Format: int32 */
            mastered: number;
        };
        ServerInfo: {
            name: string;
            version: string;
            event_names: string[];
            /** Format: int32 */
            subscribers: number;
        };
        Catalog: {
            chat: components["schemas"]["ProviderOption"][];
            realtime: components["schemas"]["ProviderOption"][];
            roles: components["schemas"]["RoleOption"][];
        };
        ModelOption: {
            value: string;
            label: string;
        };
        ProviderOption: {
            key: string;
            label: string;
            credential_key: string;
            console_url: string;
            default_model: string;
            models: string[];
            voices: components["schemas"]["ModelOption"][];
        };
        RoleOption: {
            key: string;
            label: string;
        };
        AudioDeviceOption: {
            name: string;
            /** Format: int32 */
            index: number;
        };
        AudioDevices: {
            inputs: components["schemas"]["AudioDeviceOption"][];
            outputs: components["schemas"]["AudioDeviceOption"][];
        };
        RealtimeStateChanged: {
            connected: boolean;
            reason: string;
        };
        SpeechActivity: {
            speaking: boolean;
        };
        AudioLevel: {
            /** Format: double */
            candidate: number;
            /** Format: double */
            interviewer: number;
        };
        InterviewerSpeaking: {
            speaking: boolean;
        };
        TranscriptDelta: {
            speaker: string;
            text: string;
        };
        TranscriptCommitted: {
            /** Format: int32 */
            turn_id: number;
            speaker: string;
            text: string;
            /** Format: int64 */
            started_at_ms: number;
            /** Format: int64 */
            duration_ms: number;
        };
        PhaseChanged: {
            phase: components["schemas"]["InterviewPhase"];
            reason: string;
        };
        DirectorDecided: {
            intent: components["schemas"]["TurnIntent"];
            brief: string;
            target_skill: string;
            /** Format: int32 */
            follow_up_depth: number;
        };
        DriftDetected: {
            kind: components["schemas"]["DriftKind"];
            excerpt: string;
            repaired: boolean;
        };
        ReanchorPerformed: {
            /** Format: int32 */
            turn_index: number;
            trigger: string;
        };
        CopilotHint: {
            keywords: string[];
            outline: string[];
            caution: string;
        };
        StarProgress: {
            present: components["schemas"]["StarElement"][];
            missing: components["schemas"]["StarElement"][];
            is_behavioral: boolean;
        };
        InterruptionFired: {
            by_interviewer: boolean;
            reason: string;
        };
        LiveAnnotation: {
            /** Format: int32 */
            turn_id: number;
            kind: components["schemas"]["AnnotationKind"];
            comment: string;
        };
        LiveScoreUpdated: {
            scores: {
                [key: string]: number;
            };
        };
        CodeSubmitted: {
            language: string;
            source: string;
        };
        EngineFailure: {
            user_message: string;
            detail: string;
            fatal: boolean;
        };
        ProsodySnapshot: {
            /** Format: double */
            words_per_minute: number;
            /** Format: double */
            filler_ratio: number;
            /** Format: double */
            pause_ratio: number;
            /** Format: int64 */
            longest_pause_ms: number;
        };
        ReviewProgress: {
            stage: string;
            /** Format: int32 */
            percent: number;
            detail: string;
        };
        ElapsedTick: {
            /** Format: int64 */
            elapsed_ms: number;
            /** Format: int64 */
            remaining_ms: number;
        };
        TaskProgress: {
            task_id: string;
            stage: string;
            /** Format: int32 */
            percent: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateReviewBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewReport"];
                };
            };
        };
    };
    scan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InterruptedSession"][];
                };
            };
        };
    };
    buildSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildSessionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InterviewState"];
                };
            };
        };
    };
    ingestResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPathBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredResume"];
                };
            };
        };
    };
    ingestJobText: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestJobTextBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredJob"];
                };
            };
        };
    };
    synthesizeJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesizeJobBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredJob"];
                };
            };
        };
    };
    ingestJobFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestPathBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredJob"];
                };
            };
        };
    };
    diagnose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredGap"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonaContract"][];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaContract"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonaContract"];
                };
            };
        };
    };
    uniqueName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniqueNameBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    setMastered: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMasteredBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    waitFinished: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopInterviewBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StopResult"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartInterviewBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    mute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MuteBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    interrupt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    hint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HintBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    finishEarly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    submitCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitCodeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppSettings"];
                };
            };
        };
    };
    save_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    probe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProbeOutcome"];
                };
            };
        };
    };
    setKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCodeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RunOutcome"];
                };
            };
        };
    };
    judge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgeCodeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JudgeOutcome"];
                };
            };
        };
    };
    challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComposeChallengeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CodingChallenge"];
                };
            };
        };
    };
    overall: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrendPoint"][];
                };
            };
        };
    };
    dimensions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["TrendPoint"][];
                    };
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    turns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TurnRecord"][];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionStatus"];
                };
            };
        };
    };
    state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InterviewState"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GlobalStats"];
                };
            };
        };
    };
    load: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewReport"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                include_mastered?: boolean;
                topic?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredMistake"][];
                };
            };
        };
    };
    topics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    counts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MistakeCounts"];
                };
            };
        };
    };
    resumes: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredResume"][];
                };
            };
        };
    };
    jobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredJob"][];
                };
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ServerInfo"];
                };
            };
        };
    };
    keyPresent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Catalog"];
                };
            };
        };
    };
    audioDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AudioDevices"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mistake_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Ok"];
                };
            };
        };
    };
}
